# Gerado pelo módulo de configurações do Quickshell.
# NÃO edite manualmente — suas mudanças serão sobrescritas na
# próxima vez que salvar pelo shell. Edite hyprland.conf à
# vontade; este arquivo só existe pra não mexer nele direto.

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(8aadf4ff)
    col.inactive_border = rgba(2c2f42aa)
}

decoration {
    rounding = 15
}

