#!/usr/bin/env python3
import os
import sys
import json
import subprocess

if len(sys.argv) < 2:
    print("Uso: aplicar_tema.py <caminho_do_tema.json>")
    sys.exit(1)

theme_path = sys.argv[1]
if not os.path.exists(theme_path):
    print(f"Erro: Arquivo não encontrado: {theme_path}")
    sys.exit(1)

with open(theme_path, 'r') as f:
    dados = json.load(f)

HOME = os.path.expanduser("~")
PATHS = {
    "quickshell": os.path.join(HOME, ".config", "quickshell", "theme-colors.json"),
    "hypr_colors": os.path.join(HOME, ".config", "hypr", "colors.conf"),
    "hyprpaper": os.path.join(HOME, ".config", "hypr", "hyprpaper.conf"),
    "vicinae_dir": os.path.join(HOME, ".local", "share", "vicinae", "themes"),
    "kitty": os.path.join(HOME, ".config", "kitty", "theme.conf"),
    "gtk3": os.path.join(HOME, ".config", "gtk-3.0", "gtk.css")
}

fundo, superficie, base = dados.get('fundo', '141019'), dados.get('superficie', '201931'), dados.get('base', '332844')
destaque1, destaque2, texto = dados.get('destaque1', '9A7BB5'), dados.get('destaque2', 'C77B7B'), dados.get('texto', 'EEE8F5')
wall = dados.get('wallpaper', '')
tema_id = os.path.basename(theme_path).replace(".json", "")

# 1. Quickshell
with open(PATHS["quickshell"], "w") as f:
    json.dump(dados, f, indent=2)

# 2. Hyprland Colors
with open(PATHS["hypr_colors"], "w") as f:
    f.write(f"$fundo = rgb({fundo})\n$superficie = rgb({superficie})\n$base = rgb({base})\n$destaque1 = rgb({destaque1})\n$destaque2 = rgb({destaque2})\n$texto = rgb({texto})\n")

# 3. Hyprpaper
with open(PATHS["hyprpaper"], "w") as f:
    f.write(f"splash = false\nwallpaper {{\n    monitor =\n    path = {wall}\n    fit_mode = cover\n}}\n")

# 4. Vicinae
os.makedirs(PATHS["vicinae_dir"], exist_ok=True)
with open(os.path.join(PATHS["vicinae_dir"], f"{tema_id}.toml"), "w") as f:
    f.write(f'[meta]\nversion = 1\nname = "{tema_id}"\ndescription = "Theme generated by StyleAll"\nvariant = "dark"\ninherits = "vicinae-dark"\n[colors.core]\nbackground = "#{fundo}"\nforeground = "#{texto}"\nsecondary_background = "#{superficie}"\nborder = "#{base}"\naccent = "#{destaque1}"\n[colors.accents]\nred = "#{destaque2}"\n')

# 5. Kitty
os.makedirs(os.path.dirname(PATHS["kitty"]), exist_ok=True)
with open(PATHS["kitty"], "w") as f:
    f.write(f"background #{fundo}\nforeground #{texto}\nselection_background #{destaque1}\nselection_foreground #{fundo}\n")

# 5.5 Ghostty
ghostty_theme_dir = os.path.join(HOME, ".config", "ghostty", "themes")
os.makedirs(ghostty_theme_dir, exist_ok=True)
with open(os.path.join(ghostty_theme_dir, tema_id), "w") as f:
    f.write(f"background = #{fundo}\n")
    f.write(f"foreground = #{texto}\n")
    f.write(f"cursor-color = #{destaque2}\n")
    f.write(f"selection-background = #{destaque1}\n")
    f.write(f"selection-foreground = #{fundo}\n")
    # Add minimal palette mapping
    f.write(f"palette = 0=#{fundo}\n")
    f.write(f"palette = 1=#{destaque2}\n")
    f.write(f"palette = 2=#{destaque1}\n")
    f.write(f"palette = 3=#{destaque2}\n")
    f.write(f"palette = 4=#{destaque1}\n")
    f.write(f"palette = 5=#{destaque2}\n")
    f.write(f"palette = 6=#{destaque1}\n")
    f.write(f"palette = 7=#{texto}\n")
    f.write(f"palette = 8=#{superficie}\n")
    f.write(f"palette = 9=#{destaque2}\n")
    f.write(f"palette = 10=#{destaque1}\n")
    f.write(f"palette = 11=#{destaque2}\n")
    f.write(f"palette = 12=#{destaque1}\n")
    f.write(f"palette = 13=#{destaque2}\n")
    f.write(f"palette = 14=#{destaque1}\n")
    f.write(f"palette = 15=#{texto}\n")

ghostty_config = os.path.join(HOME, ".config", "ghostty", "config")
if os.path.exists(ghostty_config):
    with open(ghostty_config, "r") as f:
        lines = f.readlines()
    with open(ghostty_config, "w") as f:
        theme_found = False
        for line in lines:
            if line.startswith("theme ="):
                f.write(f'theme = {tema_id}\n')
                theme_found = True
            else:
                f.write(line)
        if not theme_found:
            f.write(f'\ntheme = {tema_id}\n')

# 6. GTK3
os.makedirs(os.path.dirname(PATHS["gtk3"]), exist_ok=True)
with open(PATHS["gtk3"], "w") as f:
    f.write(f"@define-color theme_bg_color #{fundo};\n@define-color theme_fg_color #{texto};\n@define-color theme_base_color #{superficie};\n@define-color theme_text_color #{texto};\n@define-color theme_selected_bg_color #{destaque1};\nwindow, dialog, notebook {{ background-color: @theme_bg_color; color: @theme_fg_color; }}\n")

# Reloads
subprocess.run(["hyprctl", "hyprpaper", "wallpaper", f",{wall}"], capture_output=True, check=False)
subprocess.run(["killall", "-USR1", "kitty"], capture_output=True, check=False)
subprocess.run(["hyprctl", "dispatch", "sendshortcut", "CTRL SHIFT,comma,class:com.mitchellh.ghostty"], capture_output=True, check=False)
subprocess.run(["killall", "thunar"], capture_output=True, check=False)

import time

subprocess.run(["killall", "vicinae"], capture_output=True, check=False)
subprocess.Popen(["vicinae", "server"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, stdin=subprocess.DEVNULL)
time.sleep(0.5)
subprocess.run(["vicinae", "theme", "set", tema_id], capture_output=True, check=False)

# Send IPC signal to Quickshell instead of killing it! 
# We don't want to kill the shell while the user is using the settings menu!
# Quickshell already watches theme-colors.json natively! No need to restart Quickshell!
print("Tema aplicado com sucesso.")
